name: practice_dart_01_basic_practice
description: A simple command-line application.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  equatable: ^2.0.3
  crypto: ^3.0.6

dev_dependencies:
  lints: ^3.0.0
  test: ^1.22.2
